include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    type_annotate_public_apis: false
    unnecessary_brace_in_string_interps: false
    lines_longer_than_80_chars: false